const NAVSITE = {
    "导航": [
        {href: "https://www.acgbus.com/", image: "https://www.acgbus.com/favicon.ico", title: "ACG巴士"},
        {href: "https://www.acgbox.link/", image: "https://www.acgbox.link/wp-content/uploads/logo/86742914_p0.png", title: "ACG盒子"},
        {href: "https://www.miaoaaa.com/", image: "https://www.miaoaaa.com/logo/favicon.png", title: "ACG喵导航"},
        {href: "https://acg123.top/", image: "https://acg123.top/wp-content/uploads/2022/02/favicon.ico", title: "次元导航"},
        {href: "https://acgnav.cn/", image: "https://acgnav.cn/assets/images/favicon.png", title: "导航姬"},
        {href: "https://www.acg123.co/", image: "https://www.acg123.co/favicon.ico", title: "二刺螈导航"},
        {href: "https://www.moe-box.com/", image: "http://www.moe-box.com/wp-content/uploads/2022/02/翼萌导航.webp", title: "Moebox"},
        {href: "https://myacg.online/", image: "https://img.zjgsuzjx.top/img/images/2021/05/31/a7da6f8d4a1ff0c8a8a87094d198d368.th.jpg", title: "MyACG"},
        {href: "https://v2fd.com/", image: "https://v2fd.com/favicon-32x32.png", title: "V2FD"},
        {href: "https://webjike.com/", image: "https://webjike.com/favicon.png", title: "小呆导航"},
    ],
    "搞机": [
        {href: "https://dwnld.aicp-rom.com/", image: "https://dwnld.aicp-rom.com/imgs/favicons/favicon.ico", title: "AICP"},
        {href: "https://sourceforge.net/projects/ancientrom/files/", image: "https://a.fsdn.com/allura/p/ancientrom/icon?w=90", title: "AncientOS"},
        {href: "https://www.arrowos.net/", image: "https://www.arrowos.net/img/logo.png", title: "ArrowOS"},
        {href: "https://sourceforge.net/projects/project-awaken/files/", image: "https://a.fsdn.com/allura/p/project-awaken/icon", title: "Awaken OS"},
        {href: "https://get.carbonrom.org/", image: "https://get.carbonrom.org/assets/favicon/favicon.ico", title: "CarbonROM"},
        {href: "https://sourceforge.net/projects/cherish-os/files/device/", image: "https://cherishos.com/assets/img/cherish.svg", title: "CherishOS"},
        {href: "https://sourceforge.net/projects/conqueros/files/", image: "https://a.fsdn.com/allura/p/conqueros/icon?w=90", title: "ConquerOS"},
        {href: "https://sourceforge.net/projects/crdroid/files/", image: "images/icons/crdroid.ico", title: "crdroid"},
        {href: "https://sourceforge.net/projects/derpfest/files/", image: "https://a.fsdn.com/allura/p/derpfest/icon?w=90", title: "DerpFest"},
        {href: "https://divestos.org/", image: "https://divestos.org/images/favicon.png", title: "DivestOS"},
        {href: "https://www.droidontime.com/", image: "https://www.droidontime.com/assets/images/icon.webp", title: "dotOS"},
        {href: "https://sourceforge.net/projects/evolution-x/files/", image: "https://a.fsdn.com/allura/p/evolution-x/icon?w=90", title: "Evolution X"},
        {href: "https://projectfluid.org/", image: "https://projectfluid.org/fluid.svg", title: "fluid"},
        {href: "https://havoc-os.com/", image: "https://havoc-os.com/src/img/favicon.svg", title: "Havoc-OS"},
        {href: "https://kaleidoscope.ink/", image: "https://kaleidoscope.ink/images/favicon.png", title: "Kaleidoscope"},
        {href: "https://download.lineageos.org/", image: "https://download.lineageos.org/favicon.ico", title: "LineageOS"},
        {href: "https://sourceforge.net/projects/nameless-aosp/files/kebab/", image: "https://a.fsdn.com/allura/p/nameless-aosp/icon?w=90", title: "Nameless"},
        {href: "https://nusantararom.org/", image: "https://nusantararom.org/favicon.png", title: "NusantaraROM"},
        {href: "https://paranoidandroid.co/", image: "https://paranoidandroid.co/favicon-32x32.png", title: "Paranoid"},
        {href: "https://sourceforge.net/projects/pixelextended/files/", image: "https://a.fsdn.com/allura/p/pixelextended/icon?w=90", title: "Pixel Extended"},
        {href: "https://get.pixelexperience.org/", image: "images/icons/pixelexperience.png", title: "pixelexperience"},
        {href: "https://ppui.site/", image: "https://ppui.site/assets/images/pixelpluslogo2.png", title: "PixelPlusUI"},
        {href: "https://pixysos.com/", image: "https://pixysos.com/static/images/favicon.png", title: "PixysOS"},
        {href: "https://dl.project404.xyz/", image: "https://dl.project404.xyz/images/favicon.svg", title: "Project 404"},
        {href: "https://projectarcana-aosp.netlify.app/", image: "https://projectarcana-aosp.netlify.app/logo-transparent.png", title: "Project Arcana"},
        {href: "https://sourceforge.net/projects/projectblaze/files/", image: "https://a.fsdn.com/allura/p/projectblaze/icon?w=90", title: "Project Blaze"},
        {href: "https://sourceforge.net/projects/project-elixir/files/", image: "https://a.fsdn.com/allura/p/project-elixir/icon?w=90", title: "Project Elixir"},
        {href: "https://sourceforge.net/projects/projectmatrixx/files/", image: "https://a.fsdn.com/allura/p/projectmatrixx/icon?w=90", title: "Project Matrixx"},
        {href: "https://sourceforge.net/projects/projectsakura/files/", image: "https://a.fsdn.com/allura/p/projectsakura/icon?w=90", title: "Project Sakura"},
        {href: "https://sourceforge.net/projects/superioros/files/", image: "https://a.fsdn.com/allura/p/superioros/icon?w=90", title: "Superior OS"},
        {href: "https://syberiaos.com/", image: "https://syberiaos.com/favicon.ico", title: "Syberia OS"},
        {href: "https://tequilaos.org/download", image: "https://tequilaos.org/tequila_logo.svg", title: "tequilaOS"},
        {href: "https://project-xtended.org/", image: "https://project-xtended.org/img/favicon.ico", title: "Xtended"},
    ],
    "no-1": [
        {href: "https://orangefox.download/", image: "https://orangefox.download/icons/favicon.ico", title: "OrangeFox"},
        {href: "https://skyhawkrecovery.github.io/", image: "https://skyhawkrecovery.github.io/img/favICO.png", title: "SHRP"},
        {href: "https://twrp.me/", image: "https://twrp.me/favicon.ico", title: "TWRP"},
    ],
    "no-2": [
        {href: "https://github.com/BiTGApps/BiTGApps-Release/releases/", image: "https://github.githubassets.com/favicons/favicon.svg", title: "BiTGApps"},
        {href: "https://sourceforge.net/projects/flamegapps/files/arm64/", image: "https://a.fsdn.com/con/img/sandiego/svg/originals/sf-icon-orange-no_sf.svg", title: "FlameGApps"},
        {href: "https://sourceforge.net/projects/nikgapps/files/Releases/", image: "https://a.fsdn.com/con/img/sandiego/svg/originals/sf-icon-orange-no_sf.svg", title: "NikGApps"},
        {href: "https://opengapps.org/", image: "https://opengapps.org/images/android-icon-144x144.png", title: "Open GApps"},
    ],
    "机场": [
        {href: "https://1.akcaaaa.com/", image: "https://1.akcaaaa.com/favicon.ico", title: "Akkcloud"},
        {href: "https://dukou.io/", image: "https://dukou.io/logo.ico", title: "Dukou"},
        {href: "https://www.efcloud1.com/", image: "https://www.efcloud1.com//theme/Aurora/favicon.svg", title: "EFCloud"},
        {href: "https://front.spaport.top/", image: "images/icons/SpaPort.png", title: "SpaPort"},
    ],
    "教程": [
        {href: "https://www.runoob.com/", image: "images/icons/菜鸟教程.ico", title: "菜鸟教程"},
        {href: "https://www.jc2182.com/", image: "https://www.jc2182.com/wp-content/themes/wiki/images/favicon.ico", title: "蝴蝶教程"},
        {href: "https://www.w3school.com.cn/", image: "https://www.w3school.com.cn/ui2019/logo-32-red.png", title: "W3School"},
    ],
    "论坛": [
        {href: "https://2dfan.com/", image: "https://2dfan.com/favicon.ico", title: "2DFan"},
        {href: "https://acgfun.moe/", image: "https://acgfun.moe/favicon.ico", title: "AcgFun"},
        {href: "https://www.anime-sharing.com/", image: "https://www.anime-sharing.com/styles/io/images/favicon.png", title: "Anime-Sharing"},
        {href: "https://bangumi.tv/", image: "https://bangumi.tv/img/favicon.ico", title: "Bangumi"},
        {href: "https://seiya-saiga.com/", image: "https://seiya-saiga.com/image/favicon.ico", title: "誠也の部屋"},
        {href: "https://www.acgndog.com/", image: "https://www.acgndog.com/wp-content/uploads/2017/11/439c8112e53379d73724e80c93eccd0c-32x32.png", title: "次元狗"},
        {href: "https://sakustar.top/", image: "https://img.m.cn.cname4593.yjs-cdn.com/2022/07/20220729091230535.png", title: "稻荷ACG"},
        // {href: "https://erogamescape.dyndns.org/", image: "https://erogamescape.dyndns.org/favicon.ico", title: "ErogameScape"},
        {href: "https://bbs.kfpromax.com/", image: "https://bbs.kfpromax.com/favicon.ico", title: "绯月"},
        {href: "https://www.sayhuahuo.xyz/", image: "https://www.sayhuahuo.xyz/favicon.ico", title: "花火学园"},
        {href: "https://galgamer.moe/", image: "https://galgamer.moe/favicon.ico", title: "Galgamer"},
        {href: "https://gallibrary.pw/", image: "https://gallibrary.pw/favicon.ico", title: "GAL图书馆"},
        {href: "https://www.clfans.club/", image: "https://www.clfans.club/wp-content/uploads/2022/10/277693ee57201208.jpg", title: "光坂小镇"},
        {href: "https://www.kungal.com/", image: "https://www.kungal.com/favicon.ico", title: "鲲Galgame论坛"},
        {href: "https://lzacg.org/", image: "images/icons/量子ACG.jpeg", title: "量子ACG"},
        {href: "https://blog.reimu.net/", image: "https://blog.reimu.net/wp-content/uploads/2016/02/cropped-logo-32x32.png", title: "灵梦御所"},
        {href: "https://www.hacg.lv/", image: "https://www.hacg.lv/favicon.ico", title: "琉璃神社"},
        {href: "http://www.acgjc.com/", image: "images/icons/漫音社.ico", title: "漫音社"},
        {href: "https://www.hmoeh.com/", image: "https://www.hmoeh.com/favicon.ico", title: "萌幻之乡"},
        {href: "https://bbs.mikocon.com/", image: "https://bbs.mikocon.com/favicon.ico", title: "Mikocon"},
        {href: "https://bbs.mihoyo.com/", image: "https://img-static.mihoyo.com/favicon.ico", title: "米游社"},
        {href: "https://www.ttloli.com/", image: "https://www.ttloli.com/favicon.ico", title: "MyGalgame"},
        {href: "https://www.blue-plus.net/", image: "https://www.blue-plus.net/favicon.ico", title: "南+"},
        {href: "https://www.soraacg.com/", image: "https://www.soraacg.com/wp-content/uploads/2022/12/网站图标.png", title: "穹之下"},
        // {href: "https://post.qingjuacg.top/", image: "https://post.qingjuacg.top/favicon.ico", title: "青桔网"},
        {href: "https://hexo.acgus.top/", image: "https://hexo.acgus.top/favicon.ico", title: "青桔网"},
        {href: "https://cangku.moe/", image: "https://cangku.moe/favicon.ico", title: "绅士仓库"},
        {href: "https://www.aigalgame.com/", image: "images/icons/绅士天堂.ico", title: "绅士天堂"},
        {href: "https://www.shinnku.com/", image: "https://www.shinnku.com/favicon.ico", title: "失落小站"},
        {href: "https://www.tiangal.com/", image: "https://www.tiangal.com/wp-content/uploads/2022/04/2022042217411468.png", title: "天遊二次元"},
        {href: "https://www.touchgal.org/", image: "https://npm.elemecdn.com/touchgalstatic1@0.0.3/img/CnLIp.png", title: "TouchGAL"},
        {href: "https://vndb.org/", image: "https://vndb.org/favicon.ico", title: "VNDB"},
        {href: "https://t-satoru.top/", image: "https://t-satoru.top/favicon.ico", title: "小鳥遊暁"},
        {href: "https://xxacg.net/", image: "https://xxacg.net/wp-content/uploads/2021/03/cropped-game-1-32x32.png", title: "xxacg"},
        {href: "https://www.yngal.com/", image: "https://www.yngal.com/static/images/icon.jpg", title: "XXGalgame"},
        // {href: "https://ercygame.com/", image: "https://ercygame.com/wp-content/uploads/2021/07/cropped-srchttp___inews.gtimg_.com_newsapp_match_0_10723316324_0-1.jpgreferhttp___inews.gtimg_-1-32x32.jpg", title: "幽隐恋梦"},
        {href: "http://sagaoz.net/foolmaker/", image: "http://sagaoz.net/favicon.ico", title: "愚者の館"},
        {href: "https://www.ymgal.games/", image: "https://www.ymgal.games/favicon.ico", title: "月幕Galgame"},
        // {href: "https://bbs.zdfx.net/", image: "https://bbs.zdfx.net/img/zdfx.svg", title: "终点"},
        {href: "https://bbs.drdian.net/", image: "https://bbs.drdian.net/img/zdfx.svg", title: "终点"},
        {href: "https://gkdworld.eu.org/", image: "https://gkdworld.eu.org/favicon.ico", title: "资源统筹局"},
        {href: "https://zodgame.xyz/", image: "images/icons/ZodGame论坛.ico", title: "ZodGame论坛"},
        {href: "https://www.erogame.space/", image: "https://www.erogame.space/wp-content/uploads/2023/09/1694188211-611f695c2a6f1-bpfull.jpg", title: "ファウスト"},
        {href: "https://wafuwafu.com/", image: "https://wafuwafu.com/wp-content/uploads/2022/09/kud_wafter_favicon.png", title: "わふわふ"},
    ],
    "no-3": [
        {href: "https://www.423down.com/", image: "https://www.423down.com/wp-content/themes/D7/img/favicon.ico", title: "423Down"},
        {href: "https://apphot.cc/", image: "https://apphot.cc/wp-content/uploads/2020/10/cropped-apphot-1-32x32.png", title: "App热"},
        {href: "https://greasyfork.org/", image: "https://greasyfork.org//vite/assets/blacklogo16-37ZGLlXh.png", title: "Greasy Fork"},
        {href: "https://www.ghxi.com/", image: "https://www.ghxi.com/favicon.ico", title: "果核剥壳"},
        {href: "https://next.itellyou.cn/", image: "https://next.itellyou.cn/favicon.ico", title: "ITELLYOU"},
        {href: "https://www.kelongwo.com/", image: "https://img.quankexia.com/kelongwo/wp-content/uploads/2021/07/2021071214094981-150x150.png", title: "克隆网"},
        {href: "https://forum.mobilism.org/", image: "https://forum.mobilism.org/favicon.ico", title: "Mobilism"},
        {href: "https://www.puresys.net/", image: "https://www.puresys.net/favicon.ico", title: "Puresys"},
        {href: "https://myqqjd.com/", image: "https://myqqjd.com/wp-content/logo/favicon.ico", title: "芊芊精典"},
        {href: "https://rsload.net/", image: "https://rsload.net/favicon.ico", title: "rsload"},
        {href: "https://itrmb.com/", image: "https://itrmb.com/view/img/favicon.ico", title: "数字人民币"},
        {href: "https://www.52pojie.cn/", image: "https://www.52pojie.cn/favicon.ico", title: "吾爱破解"},
        {href: "https://www.whg6.com/", image: "https://www.whg6.com/favicon.ico", title: "无痕哥"},
        {href: "https://forum.xda-developers.com/", image: "https://forum.xda-developers.com/data/assets/logo/favicon-32x32.png", title: "XDA"},
    ],
    "商城": [
        {href: "https://www.dlsite.com/", image: "https://www.dlsite.com/images/web/common/favicon.ico", title: "DLsite"},
        {href: "https://store.epicgames.com/", image: "https://static-assets-prod.epicgames.com/epic-store/static/favicon.ico", title: "EPIC"},
        {href: "https://jastusa.com/", image: "https://jastusa.com/fav.ico", title: "JAST"},
        {href: "https://www.jd.com/", image: "https://www.jd.com/favicon.ico", title: "京东"},
        {href: "https://www.taobao.com/", image: "https://www.taobao.com/favicon.ico", title: "淘宝"},
    ],
    "社交": [
        {href: "https://tieba.baidu.com/", image: "https://tb3.bdstatic.com/public/icon/favicon-v2.ico", title: "百度贴吧"},
        {href: "https://twitter.com/", image: "https://abs.twimg.com/favicons/twitter.2.ico", title: "Twitter"},
        {href: "https://weibo.com/", image: "https://weibo.com/favicon.ico", title: "微博"},
        {href: "https://www.zhihu.com/", image: "https://static.zhihu.com/heifetz/favicon.ico", title: "知乎"},
    ],
    "搜索": [
        {href: "https://www.baidu.com/", image: "https://www.baidu.com/favicon.ico", title: "百度"},
        {href: "https://www.bing.com/", image: "https://www.bing.com/sa/simg/favicon-trans-bg-blue-mg.ico", title: "Bing"},
        {href: "https://fsoufsou.com/", image: "https://static.hetaousercontent.com/static/assets/favicon.ico", title: "F搜"},
        {href: "https://www.google.com/", image: "https://www.google.com/favicon.ico", title: "Google"},
        {href: "https://www.sogou.com/", image: "https://www.sogou.com/images/logo/new/favicon.ico", title: "搜狗搜索"},
    ],
    "no-4": [
        {href: "https://www.ggbases.com/", image: "https://www.ggbases.com/favicon.ico", title: "GGBases"},
        {href: "https://nyaa.si/", image: "https://nyaa.si/static/favicon.png", title: "Nyaa"},
        {href: "https://sukebei.nyaa.si/", image: "https://sukebei.nyaa.si/static/favicon.png", title: "Sukebei"},
    ],
    "图片": [
        {href: "https://www.pixiv.net/", image: "https://www.pixiv.net/favicon.ico", title: "Pixiv"},
    ],
    "网盘": [
        {href: "https://www.123pan.com/", image: "https://www.123pan.com/static/favicon.ico", title: "123云盘"},
        {href: "https://www.aliyundrive.com/", image: "https://gw.alicdn.com/imgextra/i3/O1CN01aj9rdD1GS0E8io11t_!!6000000000620-73-tps-16-16.ico", title: "阿里云盘"},
        {href: "https://pan.baidu.com/", image: "https://nd-static.bdstatic.com/m-static/v20-main/favicon-main.ico", title: "百度网盘"},
        {href: "https://pan.quark.cn/", image: "https://image.quark.cn/s/uae/g/3o/broccoli/resource/202304/c62b4840-e344-11ed-93c7-392f83c2aa26.png", title: "夸克网盘"},
        {href: "https://pc.woozooo.com/", image: "https://pc.woozooo.com/favicon.ico", title: "蓝奏云"},
        {href: "https://mega.io/", image: "https://mega.io/favicon.ico", title: "MEGA"},
        {href: "https://mypikpak.com/", image: "https://mypikpak.com/favicon-32x32.png", title: "PikPak"},
        {href: "https://www.quqi.com/", image: "https://www.quqi.com/favicon.ico", title: "曲奇云盘"},
        {href: "https://cloud.189.cn/", image: "https://cloud.189.cn/web/logo.ico", title: "天翼云盘"},
        {href: "https://drive.uc.cn/", image: "https://drive.uc.cn/favicon.ico", title: "UC网盘"},
    ],
    "影音": [
        {href: "https://www.acfun.cn/", image: "https://cdn.aixifan.com/ico/favicon.ico", title: "AcFun"},
        {href: "https://www.agedm.org/", image: "https://www.agedm.org//favicon.ico", title: "AGE动漫"},
        {href: "https://www.asmr.one/", image: "https://www.asmr.one/statics/icons/favicon.ico", title: "ASMR Online"},
        {href: "https://www.bilibili.com/", image: "https://www.bilibili.com/favicon.ico", title: "哔哩哔哩"},
        {href: "https://dilidili.io/", image: "https://dilidili.io/favicon.ico", title: "嘀哩嘀哩"},
        {href: "https://e-hentai.org/", image: "https://e-hentai.org/favicon.ico", title: "E-Hentai"},
        {href: "https://exhentai.org/", image: "https://exhentai.org/favicon.ico", title: "ExHentai"},
        {href: "https://www.mitang.tv/", image: "https://p.upyun.com/demo/tmp/VQdWNWSr.webp", title: "蜜糖动漫"},
        {href: "https://www.quqim.net/", image: "https://www.quqim.net/tpsf/qd_pic/favicon.ico", title: "曲奇动漫"},
        {href: "https://music.163.com/", image: "https://s1.music.126.net/style/favicon.ico", title: "网易云音乐"},
        {href: "https://www.5dm.link/", image: "https://www.5dm.link/favicon.ico", title: "五弹幕"},
        {href: "http://www.yhdmba.org/", image: "images/icons/樱花动漫.ico", title: "樱花动漫"},
        {href: "https://www.yhmgo.com/", image: "https://www.yhmgo.com//tpsf/yh_pic/favicon.ico", title: "樱花动漫"},
    ],
    "资讯": [
        {href: "https://www.expreview.com/", image: "https://www.expreview.com/favicon.ico", title: "超能网"},
        {href: "https://www.landiannews.com/", image: "https://static.lancdn.com/landian/v4.0.1/images/favicon.png", title: "蓝点网"},
    ]
}

const FORM = {
    "搜索": {
        "百度": {action: "https://www.baidu.com/s", name: "wd", method: "", image: "https://www.baidu.com/favicon.ico"},
        Bing: {action: "https://www.bing.com/search", name: "q", method: "", image: "https://www.bing.com/sa/simg/favicon-trans-bg-blue-mg.ico"},
        F搜: {action: "https://fsoufsou.com/search", name: "q", method: "", image: "https://static.hetaousercontent.com/static/assets/favicon.ico"},
        Google: {action: "https://www.google.com/search", name: "q", method: "", image: "https://www.google.com/favicon.ico"},
        "搜狗": {action: "https://www.sogou.com/web", name: "query", method: "", image: "https://www.sogou.com/images/logo/new/favicon.ico"}
    },
    "磁力": {
        GGBases: {action: "https://www.ggbases.com/search.so", name: "title", method: "", image: "https://www.ggbases.com/favicon.ico"},
        Nyaa: {action: "https://nyaa.si/", name: "q", method: "", image: "https://nyaa.si/static/favicon.png"},
        Sukebei: {action: "https://sukebei.nyaa.si/", name: "q", method: "", image: "https://sukebei.nyaa.si/static/favicon.png"},
    },
    "游戏": {
        "2DFan": {action: "https://galge.fun/subjects/search", name: "keyword", method: "", image: "https://galge.fun/favicon.ico"},
        "Anime-Sharing": {action: "https://www.anime-sharing.com/search", name: "q", method: "", image: "https://www.anime-sharing.com/styles/io/images/favicon.png"},
        Bangumi: {action: "https://bangumi.tv/subject_search", name: "search_text", method: "post", image: "https://bangumi.tv/img/favicon.ico"},
        Mikocon: {action: "https://bbs.mikocon.com/search.php", name: "srchtxt", method: "", image: "https://bbs.mikocon.com/favicon.ico"},
        MyGalgame: {action: "https://www.ttloli.com", name: "s", method: "", image: "https://www.ttloli.com/favicon.ico"},
        VNDB: {action: "https://vndb.org/v", name: "sq", method: "", image: "https://vndb.org/favicon.ico"},
    }
}